namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/FollowJointTrajectoryActionResult", "c4fb3b000dc9da4fd99699380efcc5d9", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nFollowJointTrajectoryResult result\n")]
    public partial class FollowJointTrajectoryActionResult : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public FollowJointTrajectoryResult result
        {
            get;
            set;
        }

        public FollowJointTrajectoryActionResult(): base()
        {
        }

        public FollowJointTrajectoryActionResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            result.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            result = new FollowJointTrajectoryResult(binaryReader);
        }
    }
}