namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/FollowJointTrajectoryAction", "bc4f9b743838566551c0390c65f1a248", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nFollowJointTrajectoryActionGoal action_goal\nFollowJointTrajectoryActionResult action_result\nFollowJointTrajectoryActionFeedback action_feedback\n")]
    public partial class FollowJointTrajectoryAction : RosMsg
    {
        public FollowJointTrajectoryActionGoal action_goal
        {
            get;
            set;
        }

        public FollowJointTrajectoryActionResult action_result
        {
            get;
            set;
        }

        public FollowJointTrajectoryActionFeedback action_feedback
        {
            get;
            set;
        }

        public FollowJointTrajectoryAction(): base()
        {
        }

        public FollowJointTrajectoryAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new FollowJointTrajectoryActionGoal(binaryReader);
            action_result = new FollowJointTrajectoryActionResult(binaryReader);
            action_feedback = new FollowJointTrajectoryActionFeedback(binaryReader);
        }
    }
}