namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/GripperCommandActionFeedback", "653dff30c045f5e6ff3feb3409f4558d", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GripperCommandFeedback feedback
")]
    public partial class GripperCommandActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public GripperCommandFeedback feedback
        {
            get;
            set;
        }

        public GripperCommandActionFeedback(): base()
        {
        }

        public GripperCommandActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new GripperCommandFeedback(binaryReader);
        }
    }
}