namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/GripperCommandGoal", "86fd82f4ddc48a4cb6856cfa69217e43", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nGripperCommand command\n")]
    public partial class GripperCommandGoal : RosMsg
    {
        public GripperCommand command
        {
            get;
            set;
        }

        public GripperCommandGoal(): base()
        {
        }

        public GripperCommandGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            command.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            command = new GripperCommand(binaryReader);
        }
    }
}