namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/GripperCommandActionResult", "143702cb2df0f163c5283cedc5efc6b6", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nGripperCommandResult result\n")]
    public partial class GripperCommandActionResult : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public GripperCommandResult result
        {
            get;
            set;
        }

        public GripperCommandActionResult(): base()
        {
        }

        public GripperCommandActionResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            result.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            result = new GripperCommandResult(binaryReader);
        }
    }
}