namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/JointTrajectoryResult", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n")]
    public partial class JointTrajectoryResult : RosMsg
    {
        public JointTrajectoryResult(): base()
        {
        }

        public JointTrajectoryResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}