namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/JointTrajectoryFeedback", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\n")]
    public partial class JointTrajectoryFeedback : RosMsg
    {
        public JointTrajectoryFeedback(): base()
        {
        }

        public JointTrajectoryFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}