namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/JointTrajectoryActionGoal", "a99e83ef6185f9fdd7693efe99623a86", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nJointTrajectoryGoal goal\n")]
    public partial class JointTrajectoryActionGoal : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalID goal_id
        {
            get;
            set;
        }

        public JointTrajectoryGoal goal
        {
            get;
            set;
        }

        public JointTrajectoryActionGoal(): base()
        {
        }

        public JointTrajectoryActionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            goal_id.Serilize(binaryWriter);
            goal.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            goal_id = new actionlib_msgs.GoalID(binaryReader);
            goal = new JointTrajectoryGoal(binaryReader);
        }
    }
}