namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/JointTrajectoryAction", "a04ba3ee8f6a2d0985a6aeaf23d9d7ad", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nJointTrajectoryActionGoal action_goal\nJointTrajectoryActionResult action_result\nJointTrajectoryActionFeedback action_feedback\n")]
    public partial class JointTrajectoryAction : RosMsg
    {
        public JointTrajectoryActionGoal action_goal
        {
            get;
            set;
        }

        public JointTrajectoryActionResult action_result
        {
            get;
            set;
        }

        public JointTrajectoryActionFeedback action_feedback
        {
            get;
            set;
        }

        public JointTrajectoryAction(): base()
        {
        }

        public JointTrajectoryAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new JointTrajectoryActionGoal(binaryReader);
            action_result = new JointTrajectoryActionResult(binaryReader);
            action_feedback = new JointTrajectoryActionFeedback(binaryReader);
        }
    }
}