namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/JointTrajectoryGoal", "2a0eff76c870e8595636c2a562ca298e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\ntrajectory_msgs/JointTrajectory trajectory\n")]
    public partial class JointTrajectoryGoal : RosMsg
    {
        public trajectory_msgs.JointTrajectory trajectory
        {
            get;
            set;
        }

        public JointTrajectoryGoal(): base()
        {
        }

        public JointTrajectoryGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            trajectory.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            trajectory = new trajectory_msgs.JointTrajectory(binaryReader);
        }
    }
}