namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/PointHeadActionFeedback", "33c9244957176bbba97dd641119e8460", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
PointHeadFeedback feedback
")]
    public partial class PointHeadActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public PointHeadFeedback feedback
        {
            get;
            set;
        }

        public PointHeadActionFeedback(): base()
        {
        }

        public PointHeadActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new PointHeadFeedback(binaryReader);
        }
    }
}