namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/SingleJointPositionResult", "d41d8cd98f00b204e9800998ecf8427e", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
")]
    public partial class SingleJointPositionResult : RosMsg
    {
        public SingleJointPositionResult(): base()
        {
        }

        public SingleJointPositionResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}