namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/SingleJointPositionActionFeedback", "3503b7cf8972f90d245850a5d8796cfa", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nSingleJointPositionFeedback feedback\n")]
    public partial class SingleJointPositionActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public SingleJointPositionFeedback feedback
        {
            get;
            set;
        }

        public SingleJointPositionActionFeedback(): base()
        {
        }

        public SingleJointPositionActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new SingleJointPositionFeedback(binaryReader);
        }
    }
}