namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/SingleJointPositionActionGoal", "4b0d3d091471663e17749c1d0db90f61", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nSingleJointPositionGoal goal\n")]
    public partial class SingleJointPositionActionGoal : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalID goal_id
        {
            get;
            set;
        }

        public SingleJointPositionGoal goal
        {
            get;
            set;
        }

        public SingleJointPositionActionGoal(): base()
        {
        }

        public SingleJointPositionActionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            goal_id.Serilize(binaryWriter);
            goal.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            goal_id = new actionlib_msgs.GoalID(binaryReader);
            goal = new SingleJointPositionGoal(binaryReader);
        }
    }
}