namespace Roslin.Msg.control_msgs
{
    [MsgInfo("control_msgs/SingleJointPositionGoal", "fbaaa562a23a013fd5053e5f72cbb35c", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64 position
duration min_duration
float64 max_velocity
")]
    public partial class SingleJointPositionGoal : RosMsg
    {
        public System.Double position
        {
            get;
            set;
        }

        public System.TimeSpan min_duration
        {
            get;
            set;
        }

        public System.Double max_velocity
        {
            get;
            set;
        }

        public SingleJointPositionGoal(): base()
        {
        }

        public SingleJointPositionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(position);
            binaryWriter.Write(min_duration);
            binaryWriter.Write(max_velocity);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            position = binaryReader.ReadDouble();
            min_duration = binaryReader.ReadTimeSpan();
            max_velocity = binaryReader.ReadDouble();
        }
    }
}