namespace Roslin.Msg.turtle_actionlib
{
    [MsgInfo("turtle_actionlib/ShapeGoal", "3b9202ab7292cebe5a95ab2bf6b9c091", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#goal definition\nint32 edges\nfloat32 radius\n")]
    public partial class ShapeGoal : RosMsg
    {
        public System.Int32 edges
        {
            get;
            set;
        }

        public System.Single radius
        {
            get;
            set;
        }

        public ShapeGoal(): base()
        {
        }

        public ShapeGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(edges);
            binaryWriter.Write(radius);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            edges = binaryReader.ReadInt32();
            radius = binaryReader.ReadSingle();
        }
    }
}