namespace Roslin.Msg.turtle_actionlib
{
    [MsgInfo("turtle_actionlib/ShapeFeedback", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback\n\n\n")]
    public partial class ShapeFeedback : RosMsg
    {
        public ShapeFeedback(): base()
        {
        }

        public ShapeFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}