namespace Roslin.Msg.turtle_actionlib
{
    [MsgInfo("turtle_actionlib/ShapeActionGoal", "dbfccd187f2ec9c593916447ffd6cc77", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nShapeGoal goal\n")]
    public partial class ShapeActionGoal : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalID goal_id
        {
            get;
            set;
        }

        public ShapeGoal goal
        {
            get;
            set;
        }

        public ShapeActionGoal(): base()
        {
        }

        public ShapeActionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            goal_id.Serilize(binaryWriter);
            goal.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            goal_id = new actionlib_msgs.GoalID(binaryReader);
            goal = new ShapeGoal(binaryReader);
        }
    }
}