namespace Roslin.Msg.actionlib_tutorials
{
    [MsgInfo("actionlib_tutorials/AveragingAction", "628678f2b4fa6a5951746a4a2d39e716", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

AveragingActionGoal action_goal
AveragingActionResult action_result
AveragingActionFeedback action_feedback
")]
    public partial class AveragingAction : RosMsg
    {
        public AveragingActionGoal action_goal
        {
            get;
            set;
        }

        public AveragingActionResult action_result
        {
            get;
            set;
        }

        public AveragingActionFeedback action_feedback
        {
            get;
            set;
        }

        public AveragingAction(): base()
        {
        }

        public AveragingAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new AveragingActionGoal(binaryReader);
            action_result = new AveragingActionResult(binaryReader);
            action_feedback = new AveragingActionFeedback(binaryReader);
        }
    }
}