namespace Roslin.Msg.actionlib_tutorials
{
    [MsgInfo("actionlib_tutorials/AveragingActionFeedback", "78a4a09241b1791069223ae7ebd5b16b", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
AveragingFeedback feedback
")]
    public partial class AveragingActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public AveragingFeedback feedback
        {
            get;
            set;
        }

        public AveragingActionFeedback(): base()
        {
        }

        public AveragingActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new AveragingFeedback(binaryReader);
        }
    }
}