namespace Roslin.Msg.actionlib_tutorials
{
    [MsgInfo("actionlib_tutorials/AveragingFeedback", "9e8dfc53c2f2a032ca33fa80ec46fd4f", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback\nint32 sample\nfloat32 data\nfloat32 mean\nfloat32 std_dev\n\n")]
    public partial class AveragingFeedback : RosMsg
    {
        public System.Int32 sample
        {
            get;
            set;
        }

        public System.Single data
        {
            get;
            set;
        }

        public System.Single mean
        {
            get;
            set;
        }

        public System.Single std_dev
        {
            get;
            set;
        }

        public AveragingFeedback(): base()
        {
        }

        public AveragingFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(sample);
            binaryWriter.Write(data);
            binaryWriter.Write(mean);
            binaryWriter.Write(std_dev);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            sample = binaryReader.ReadInt32();
            data = binaryReader.ReadSingle();
            mean = binaryReader.ReadSingle();
            std_dev = binaryReader.ReadSingle();
        }
    }
}