namespace Roslin.Msg.actionlib_tutorials
{
    [MsgInfo("actionlib_tutorials/FibonacciActionFeedback", "73b8497a9f629a31c0020900e4148f07", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FibonacciFeedback feedback
")]
    public partial class FibonacciActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public FibonacciFeedback feedback
        {
            get;
            set;
        }

        public FibonacciActionFeedback(): base()
        {
        }

        public FibonacciActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new FibonacciFeedback(binaryReader);
        }
    }
}