namespace Roslin.Msg.actionlib_tutorials
{
    [MsgInfo("actionlib_tutorials/FibonacciAction", "f59df5767bf7634684781c92598b2406", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

FibonacciActionGoal action_goal
FibonacciActionResult action_result
FibonacciActionFeedback action_feedback
")]
    public partial class FibonacciAction : RosMsg
    {
        public FibonacciActionGoal action_goal
        {
            get;
            set;
        }

        public FibonacciActionResult action_result
        {
            get;
            set;
        }

        public FibonacciActionFeedback action_feedback
        {
            get;
            set;
        }

        public FibonacciAction(): base()
        {
        }

        public FibonacciAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new FibonacciActionGoal(binaryReader);
            action_result = new FibonacciActionResult(binaryReader);
            action_feedback = new FibonacciActionFeedback(binaryReader);
        }
    }
}