namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapActionGoal", "4b30be6cd12b9e72826df56b481f40e0", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GetMapGoal goal
")]
    public partial class GetMapActionGoal : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalID goal_id
        {
            get;
            set;
        }

        public GetMapGoal goal
        {
            get;
            set;
        }

        public GetMapActionGoal(): base()
        {
        }

        public GetMapActionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            goal_id.Serilize(binaryWriter);
            goal.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            goal_id = new actionlib_msgs.GoalID(binaryReader);
            goal = new GetMapGoal(binaryReader);
        }
    }
}