namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapAction", "e611ad23fbf237c031b7536416dc7cd7", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nGetMapActionGoal action_goal\nGetMapActionResult action_result\nGetMapActionFeedback action_feedback\n")]
    public partial class GetMapAction : RosMsg
    {
        public GetMapActionGoal action_goal
        {
            get;
            set;
        }

        public GetMapActionResult action_result
        {
            get;
            set;
        }

        public GetMapActionFeedback action_feedback
        {
            get;
            set;
        }

        public GetMapAction(): base()
        {
        }

        public GetMapAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new GetMapActionGoal(binaryReader);
            action_result = new GetMapActionResult(binaryReader);
            action_feedback = new GetMapActionFeedback(binaryReader);
        }
    }
}