namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapResult", "6cdd0a18e0aff5b0a3ca2326a89b54ff", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
nav_msgs/OccupancyGrid map
")]
    public partial class GetMapResult : RosMsg
    {
        public nav_msgs.OccupancyGrid map
        {
            get;
            set;
        }

        public GetMapResult(): base()
        {
        }

        public GetMapResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            map.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            map = new nav_msgs.OccupancyGrid(binaryReader);
        }
    }
}