namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapFeedback", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# no feedback\n")]
    public partial class GetMapFeedback : RosMsg
    {
        public GetMapFeedback(): base()
        {
        }

        public GetMapFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}