namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapActionResult", "ac66e5b9a79bb4bbd33dab245236c892", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapResult result
")]
    public partial class GetMapActionResult : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public GetMapResult result
        {
            get;
            set;
        }

        public GetMapActionResult(): base()
        {
        }

        public GetMapActionResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            result.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            result = new GetMapResult(binaryReader);
        }
    }
}