namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapGoal", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# Get the map as a nav_msgs/OccupancyGrid\n")]
    public partial class GetMapGoal : RosMsg
    {
        public GetMapGoal(): base()
        {
        }

        public GetMapGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}