namespace Roslin.Msg.nav_msgs
{
    [MsgInfo("nav_msgs/GetMapActionFeedback", "aae20e09065c3809e8a8e87c4c8953fd", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapFeedback feedback
")]
    public partial class GetMapActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public GetMapFeedback feedback
        {
            get;
            set;
        }

        public GetMapActionFeedback(): base()
        {
        }

        public GetMapActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new GetMapFeedback(binaryReader);
        }
    }
}