namespace Roslin.Msg.jsk_footstep_msgs
{
    [MsgInfo("jsk_footstep_msgs/PlanFootstepsActionFeedback", "c827ac0ba59dca5c1bf7b9bb97d2a1ae", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nPlanFootstepsFeedback feedback\n")]
    public partial class PlanFootstepsActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public PlanFootstepsFeedback feedback
        {
            get;
            set;
        }

        public PlanFootstepsActionFeedback(): base()
        {
        }

        public PlanFootstepsActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new PlanFootstepsFeedback(binaryReader);
        }
    }
}