namespace Roslin.Msg.jsk_footstep_msgs
{
    [MsgInfo("jsk_footstep_msgs/PlanFootstepsFeedback", "5f4757afbf7a130712f963e49c7f5f00", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# feedback
FootstepArray feedback
")]
    public partial class PlanFootstepsFeedback : RosMsg
    {
        public FootstepArray feedback
        {
            get;
            set;
        }

        public PlanFootstepsFeedback(): base()
        {
        }

        public PlanFootstepsFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            feedback = new FootstepArray(binaryReader);
        }
    }
}