namespace Roslin.Msg.jsk_footstep_msgs
{
    [MsgInfo("jsk_footstep_msgs/PlanFootstepsAction", "d801380a2d476b66f9efad45f18ff807", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nPlanFootstepsActionGoal action_goal\nPlanFootstepsActionResult action_result\nPlanFootstepsActionFeedback action_feedback\n")]
    public partial class PlanFootstepsAction : RosMsg
    {
        public PlanFootstepsActionGoal action_goal
        {
            get;
            set;
        }

        public PlanFootstepsActionResult action_result
        {
            get;
            set;
        }

        public PlanFootstepsActionFeedback action_feedback
        {
            get;
            set;
        }

        public PlanFootstepsAction(): base()
        {
        }

        public PlanFootstepsAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new PlanFootstepsActionGoal(binaryReader);
            action_result = new PlanFootstepsActionResult(binaryReader);
            action_feedback = new PlanFootstepsActionFeedback(binaryReader);
        }
    }
}