namespace Roslin.Msg.jsk_footstep_msgs
{
    [MsgInfo("jsk_footstep_msgs/PlanFootstepsResult", "951c674749b5b8b08d5eba2e3e62aedd", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# result
FootstepArray result
")]
    public partial class PlanFootstepsResult : RosMsg
    {
        public FootstepArray result
        {
            get;
            set;
        }

        public PlanFootstepsResult(): base()
        {
        }

        public PlanFootstepsResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            result.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            result = new FootstepArray(binaryReader);
        }
    }
}