namespace Roslin.Msg.tf2_msgs
{
    [MsgInfo("tf2_msgs/LookupTransformAction", "7ee01ba91a56c2245c610992dbaa3c37", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

LookupTransformActionGoal action_goal
LookupTransformActionResult action_result
LookupTransformActionFeedback action_feedback
")]
    public partial class LookupTransformAction : RosMsg
    {
        public LookupTransformActionGoal action_goal
        {
            get;
            set;
        }

        public LookupTransformActionResult action_result
        {
            get;
            set;
        }

        public LookupTransformActionFeedback action_feedback
        {
            get;
            set;
        }

        public LookupTransformAction(): base()
        {
        }

        public LookupTransformAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new LookupTransformActionGoal(binaryReader);
            action_result = new LookupTransformActionResult(binaryReader);
            action_feedback = new LookupTransformActionFeedback(binaryReader);
        }
    }
}