namespace Roslin.Msg.tf2_msgs
{
    [MsgInfo("tf2_msgs/LookupTransformFeedback", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\n")]
    public partial class LookupTransformFeedback : RosMsg
    {
        public LookupTransformFeedback(): base()
        {
        }

        public LookupTransformFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}