namespace Roslin.Msg.tf2_msgs
{
    [MsgInfo("tf2_msgs/LookupTransformResult", "3fe5db6a19ca9cfb675418c5ad875c36", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
geometry_msgs/TransformStamped transform
tf2_msgs/TF2Error error
")]
    public partial class LookupTransformResult : RosMsg
    {
        public geometry_msgs.TransformStamped transform
        {
            get;
            set;
        }

        public tf2_msgs.TF2Error error
        {
            get;
            set;
        }

        public LookupTransformResult(): base()
        {
        }

        public LookupTransformResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            transform.Serilize(binaryWriter);
            error.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            transform = new geometry_msgs.TransformStamped(binaryReader);
            error = new tf2_msgs.TF2Error(binaryReader);
        }
    }
}