namespace Roslin.Msg.sound_play
{
    [MsgInfo("sound_play/SoundRequestAction", "f990cf5de6a2f8e514e825b2c1f4810b", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

SoundRequestActionGoal action_goal
SoundRequestActionResult action_result
SoundRequestActionFeedback action_feedback
")]
    public partial class SoundRequestAction : RosMsg
    {
        public SoundRequestActionGoal action_goal
        {
            get;
            set;
        }

        public SoundRequestActionResult action_result
        {
            get;
            set;
        }

        public SoundRequestActionFeedback action_feedback
        {
            get;
            set;
        }

        public SoundRequestAction(): base()
        {
        }

        public SoundRequestAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new SoundRequestActionGoal(binaryReader);
            action_result = new SoundRequestActionResult(binaryReader);
            action_feedback = new SoundRequestActionFeedback(binaryReader);
        }
    }
}