namespace Roslin.Msg.sound_play
{
    [MsgInfo("sound_play/SoundRequestActionFeedback", "4577e8c5420cc167578de330a5e37d82", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
SoundRequestFeedback feedback
")]
    public partial class SoundRequestActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public SoundRequestFeedback feedback
        {
            get;
            set;
        }

        public SoundRequestActionFeedback(): base()
        {
        }

        public SoundRequestActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new SoundRequestFeedback(binaryReader);
        }
    }
}