namespace Roslin.Msg.sound_play
{
    [MsgInfo("sound_play/SoundRequestActionResult", "73b66cac2bdbb689595274036eae528d", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
SoundRequestResult result
")]
    public partial class SoundRequestActionResult : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public SoundRequestResult result
        {
            get;
            set;
        }

        public SoundRequestActionResult(): base()
        {
        }

        public SoundRequestActionResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            result.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            result = new SoundRequestResult(binaryReader);
        }
    }
}