namespace Roslin.Msg.sound_play
{
    [MsgInfo("sound_play/SoundRequestResult", "237faa3e32b21b083f32acf5260255a4", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
bool playing
time stamp
")]
    public partial class SoundRequestResult : RosMsg
    {
        public System.Boolean playing
        {
            get;
            set;
        }

        public System.DateTime stamp
        {
            get;
            set;
        }

        public SoundRequestResult(): base()
        {
        }

        public SoundRequestResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(playing);
            binaryWriter.Write(stamp);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            playing = binaryReader.ReadBoolean();
            stamp = binaryReader.ReadDateTime();
        }
    }
}