namespace Roslin.Msg.sound_play
{
    [MsgInfo("sound_play/SoundRequestGoal", "3bd5e9e7f60b85cc6f1b7662fe6e1903", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
SoundRequest sound_request
")]
    public partial class SoundRequestGoal : RosMsg
    {
        public SoundRequest sound_request
        {
            get;
            set;
        }

        public SoundRequestGoal(): base()
        {
        }

        public SoundRequestGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            sound_request.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            sound_request = new SoundRequest(binaryReader);
        }
    }
}