namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestRequestResult", "61c2364524499c7c5017e2f3fce7ba06", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 the_result
bool is_simple_server
")]
    public partial class TestRequestResult : RosMsg
    {
        public System.Int32 the_result
        {
            get;
            set;
        }

        public System.Boolean is_simple_server
        {
            get;
            set;
        }

        public TestRequestResult(): base()
        {
        }

        public TestRequestResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(the_result);
            binaryWriter.Write(is_simple_server);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            the_result = binaryReader.ReadInt32();
            is_simple_server = binaryReader.ReadBoolean();
        }
    }
}