namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestActionFeedback", "6d3d0bf7fb3dda24779c010a9f3eb7cb", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nTestFeedback feedback\n")]
    public partial class TestActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public TestFeedback feedback
        {
            get;
            set;
        }

        public TestActionFeedback(): base()
        {
        }

        public TestActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new TestFeedback(binaryReader);
        }
    }
}