namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestRequestFeedback", "d41d8cd98f00b204e9800998ecf8427e", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

")]
    public partial class TestRequestFeedback : RosMsg
    {
        public TestRequestFeedback(): base()
        {
        }

        public TestRequestFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}