namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestGoal", "18df0149936b7aa95588e3862476ebde", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nint32 goal\n")]
    public partial class TestGoal : RosMsg
    {
        public System.Int32 goal
        {
            get;
            set;
        }

        public TestGoal(): base()
        {
        }

        public TestGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(goal);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            goal = binaryReader.ReadInt32();
        }
    }
}