namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestRequestActionFeedback", "aae20e09065c3809e8a8e87c4c8953fd", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TestRequestFeedback feedback
")]
    public partial class TestRequestActionFeedback : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public TestRequestFeedback feedback
        {
            get;
            set;
        }

        public TestRequestActionFeedback(): base()
        {
        }

        public TestRequestActionFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            feedback = new TestRequestFeedback(binaryReader);
        }
    }
}