namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestRequestActionGoal", "1889556d3fef88f821c7cb004e4251f3", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nTestRequestGoal goal\n")]
    public partial class TestRequestActionGoal : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalID goal_id
        {
            get;
            set;
        }

        public TestRequestGoal goal
        {
            get;
            set;
        }

        public TestRequestActionGoal(): base()
        {
        }

        public TestRequestActionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            goal_id.Serilize(binaryWriter);
            goal.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            goal_id = new actionlib_msgs.GoalID(binaryReader);
            goal = new TestRequestGoal(binaryReader);
        }
    }
}