namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TestAction", "991e87a72802262dfbe5d1b3cf6efc9a", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

TestActionGoal action_goal
TestActionResult action_result
TestActionFeedback action_feedback
")]
    public partial class TestAction : RosMsg
    {
        public TestActionGoal action_goal
        {
            get;
            set;
        }

        public TestActionResult action_result
        {
            get;
            set;
        }

        public TestActionFeedback action_feedback
        {
            get;
            set;
        }

        public TestAction(): base()
        {
        }

        public TestAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new TestActionGoal(binaryReader);
            action_result = new TestActionResult(binaryReader);
            action_feedback = new TestActionFeedback(binaryReader);
        }
    }
}