namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TwoIntsFeedback", "d41d8cd98f00b204e9800998ecf8427e", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\n")]
    public partial class TwoIntsFeedback : RosMsg
    {
        public TwoIntsFeedback(): base()
        {
        }

        public TwoIntsFeedback(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
        }
    }
}