namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TwoIntsActionGoal", "684a2db55d6ffb8046fb9d6764ce0860", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nTwoIntsGoal goal\n")]
    public partial class TwoIntsActionGoal : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalID goal_id
        {
            get;
            set;
        }

        public TwoIntsGoal goal
        {
            get;
            set;
        }

        public TwoIntsActionGoal(): base()
        {
        }

        public TwoIntsActionGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            goal_id.Serilize(binaryWriter);
            goal.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            goal_id = new actionlib_msgs.GoalID(binaryReader);
            goal = new TwoIntsGoal(binaryReader);
        }
    }
}