namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TwoIntsActionResult", "3ba7dea8b8cddcae4528ade4ef74b6e7", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
TwoIntsResult result
")]
    public partial class TwoIntsActionResult : RosMsg
    {
        public std_msgs.Header header
        {
            get;
            set;
        }

        public actionlib_msgs.GoalStatus status
        {
            get;
            set;
        }

        public TwoIntsResult result
        {
            get;
            set;
        }

        public TwoIntsActionResult(): base()
        {
        }

        public TwoIntsActionResult(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            header.Serilize(binaryWriter);
            status.Serilize(binaryWriter);
            result.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            header = new std_msgs.Header(binaryReader);
            status = new actionlib_msgs.GoalStatus(binaryReader);
            result = new TwoIntsResult(binaryReader);
        }
    }
}