namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TwoIntsAction", "6d1aa538c4bd6183a2dfb7fcac41ee50", "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nTwoIntsActionGoal action_goal\nTwoIntsActionResult action_result\nTwoIntsActionFeedback action_feedback\n")]
    public partial class TwoIntsAction : RosMsg
    {
        public TwoIntsActionGoal action_goal
        {
            get;
            set;
        }

        public TwoIntsActionResult action_result
        {
            get;
            set;
        }

        public TwoIntsActionFeedback action_feedback
        {
            get;
            set;
        }

        public TwoIntsAction(): base()
        {
        }

        public TwoIntsAction(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            action_goal.Serilize(binaryWriter);
            action_result.Serilize(binaryWriter);
            action_feedback.Serilize(binaryWriter);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            action_goal = new TwoIntsActionGoal(binaryReader);
            action_result = new TwoIntsActionResult(binaryReader);
            action_feedback = new TwoIntsActionFeedback(binaryReader);
        }
    }
}