namespace Roslin.Msg.actionlib
{
    [MsgInfo("actionlib/TwoIntsGoal", "36d09b846be0b371c5f190354dd3153e", @"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int64 a
int64 b
")]
    public partial class TwoIntsGoal : RosMsg
    {
        public System.Int64 a
        {
            get;
            set;
        }

        public System.Int64 b
        {
            get;
            set;
        }

        public TwoIntsGoal(): base()
        {
        }

        public TwoIntsGoal(System.IO.BinaryReader binaryReader): base(binaryReader)
        {
        }

        public override void Serilize(System.IO.BinaryWriter binaryWriter)
        {
            binaryWriter.Write(a);
            binaryWriter.Write(b);
        }

        public override void Deserilize(System.IO.BinaryReader binaryReader)
        {
            a = binaryReader.ReadInt64();
            b = binaryReader.ReadInt64();
        }
    }
}